### ISSUE TITLE
LOG_DIRECTORY attribute suggestion

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-iis-8.5-site-stig-baseline#6]
control 'V-76845' 

Consider enhancing the attribute for LOG_DIRECTORY from 
current version:
```
LOG_DIRECTORY = attribute(
  'log_directory',
  description: 'Path of IIS log directory',
  default: 'C:\inetpub\logs\LogFiles'
)
```
To 
```
site_log_dir
    site_name_1:
    	dir: ’C:\inetpub\logs\LogFiles1'
    site_name_2:
    	dir: ’C:\inetpub\logs\LogFiles2'
    site_name_3:
    	dir: ’C:\inetpub\logs\LogFiles3'
```
This will allow us to verify the log dirs for each site individually...with the current implementation all sites will have to share a log dir
